services:
  welive:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: welive
    restart: unless-stopped
    env_file:
      - ../.env
    ports:
      - "3000:3000"
    volumes:
      - ../public/uploads:/app/public/uploads
